//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GyumriFinalVersion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GyumriFinalVersion.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT THIS WEBSITE.
        /// </summary>
        public static string AboutThisWebsite {
            get {
                return ResourceManager.GetString("AboutThisWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is your guide to experiencing Gyumri fully and authentically—whether you’re here for a weekend, a month, or making the city your new home. It brings together everything you need to explore Armenia’s cultural capital, from iconic landmarks and historic neighborhoods to offbeat adventures, cozy cafés, and local favorites..
        /// </summary>
        public static string AboutUsLong {
            get {
                return ResourceManager.GetString("AboutUsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your guide to experiencing Armenia&apos;s cultural capital.
        /// </summary>
        public static string AboutUsShort {
            get {
                return ResourceManager.GetString("AboutUsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The Website.
        /// </summary>
        public static string AboutWebsite {
            get {
                return ResourceManager.GetString("AboutWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility statement.
        /// </summary>
        public static string AccessibilityStatement {
            get {
                return ResourceManager.GetString("AccessibilityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardanants sq. 1.
        /// </summary>
        public static string AddressGyumri {
            get {
                return ResourceManager.GetString("AddressGyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri, Shirak Province, RA.
        /// </summary>
        public static string AddressGyumri2 {
            get {
                return ResourceManager.GetString("AddressGyumri2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and explore.
        /// </summary>
        public static string AndExplore {
            get {
                return ResourceManager.GetString("AndExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Time Travel.
        /// </summary>
        public static string ArchitecturalTimeTravel {
            get {
                return ResourceManager.GetString("ArchitecturalTimeTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aregak Bakery and Cafe.
        /// </summary>
        public static string AregakBakery {
            get {
                return ResourceManager.GetString("AregakBakery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidewalks Speak and Balconies Remember.
        /// </summary>
        public static string ArtTechTraditionCollide {
            get {
                return ResourceManager.GetString("ArtTechTraditionCollide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aslamazyan Sisters’ Gallery.
        /// </summary>
        public static string Aslamazyan {
            get {
                return ResourceManager.GetString("Aslamazyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorful, fearless, and full of stories—art by two iconic Armenian sisters..
        /// </summary>
        public static string AslamazyanDesc {
            get {
                return ResourceManager.GetString("AslamazyanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baked with Love, Served with Purpose..
        /// </summary>
        public static string BakedwithLove {
            get {
                return ResourceManager.GetString("BakedwithLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        public static string Cafe {
            get {
                return ResourceManager.GetString("Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Park Ferris Wheel.
        /// </summary>
        public static string CentralPark {
            get {
                return ResourceManager.GetString("CentralPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slow spin above the rooftops—see the city from a whole new angle..
        /// </summary>
        public static string CentralParkDesc {
            get {
                return ResourceManager.GetString("CentralParkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafts.
        /// </summary>
        public static string Crafts {
            get {
                return ResourceManager.GetString("Crafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Walking Supremacy.
        /// </summary>
        public static string CulturalRenaissance {
            get {
                return ResourceManager.GetString("CulturalRenaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our coupon feature is on the way – check back soon for.
        /// </summary>
        public static string CuponFeature {
            get {
                return ResourceManager.GetString("CuponFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUPON.
        /// </summary>
        public static string CuponUpperCase {
            get {
                return ResourceManager.GetString("CuponUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Culture, Small Budget – Always in Season.
        /// </summary>
        public static string DiscovertheHeartofArmenia {
            get {
                return ResourceManager.GetString("DiscovertheHeartofArmenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the obvious..
        /// </summary>
        public static string DiveDeeperIntoGyumrisHiddenGems {
            get {
                return ResourceManager.GetString("DiveDeeperIntoGyumrisHiddenGems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download App.
        /// </summary>
        public static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzitoghtsyan Museum.
        /// </summary>
        public static string DzitoghtsyanMuseum {
            get {
                return ResourceManager.GetString("DzitoghtsyanMuseum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 19th-century home that captures the spirit of old Gyumri..
        /// </summary>
        public static string DzitoghtsyanMuseumDesc {
            get {
                return ResourceManager.GetString("DzitoghtsyanMuseumDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafés with character, restaurants with soul, and flavors you won’t forget..
        /// </summary>
        public static string EatAndDrinkDesc {
            get {
                return ResourceManager.GetString("EatAndDrinkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        public static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Gyumri After Dark.
        /// </summary>
        public static string ExperienceGyumriAfterDark {
            get {
                return ResourceManager.GetString("ExperienceGyumriAfterDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city comes alive in a different way after sunset..
        /// </summary>
        public static string ExperienceGyumriAfterDarkText {
            get {
                return ResourceManager.GetString("ExperienceGyumriAfterDarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the Underground Arts Scene.
        /// </summary>
        public static string ExploretheUndergroundArtsScene {
            get {
                return ResourceManager.GetString("ExploretheUndergroundArtsScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri’s arts scene isn’t limited to its galleries and theaters..
        /// </summary>
        public static string ExploretheUndergroundArtsSceneText {
            get {
                return ResourceManager.GetString("ExploretheUndergroundArtsSceneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Express Train.
        /// </summary>
        public static string ExpressTrain {
            get {
                return ResourceManager.GetString("ExpressTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing.
        /// </summary>
        public static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll find:.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real recommendations on where to eat, sleep, and relax—based on what&apos;s truly popular, not paid
        /// placements..
        /// </summary>
        public static string Find1 {
            get {
                return ResourceManager.GetString("Find1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practical info to help you navigate life in Gyumri—transport, services, housing, remote work, and more..
        /// </summary>
        public static string Find2 {
            get {
                return ResourceManager.GetString("Find2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated listings of events, seasonal experiences, and neighborhood highlights..
        /// </summary>
        public static string Find3 {
            get {
                return ResourceManager.GetString("Find3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools to help you plan your trip, submit an event, or even
        ///ask locals your questions (upcoming)..
        /// </summary>
        public static string Find4 {
            get {
                return ResourceManager.GetString("Find4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And soon: a local coupon system offering discounts and perks at featured cafés, shops, and guesthouses around the city..
        /// </summary>
        public static string Find5 {
            get {
                return ResourceManager.GetString("Find5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Renaissance.
        /// </summary>
        public static string ForgeOfLegends {
            get {
                return ResourceManager.GetString("ForgeOfLegends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echoes of Gyumri&apos;s Past, Standing Proud.
        /// </summary>
        public static string FromEmpirestoEarthquakes {
            get {
                return ResourceManager.GetString("FromEmpirestoEarthquakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next: Getting Here.
        /// </summary>
        public static string GettingHere {
            get {
                return ResourceManager.GetString("GettingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting to/around.
        /// </summary>
        public static string GettingToAround {
            get {
                return ResourceManager.GetString("GettingToAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting to Gyumri.
        /// </summary>
        public static string GettingtoGyumri {
            get {
                return ResourceManager.GetString("GettingtoGyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  GG Shuttle.
        /// </summary>
        public static string GGTitle {
            get {
                return ResourceManager.GetString("GGTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great deals!.
        /// </summary>
        public static string greatDeals {
            get {
                return ResourceManager.GetString("greatDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesthouse.
        /// </summary>
        public static string Guesthouse {
            get {
                return ResourceManager.GetString("Guesthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri.
        /// </summary>
        public static string Gyumri {
            get {
                return ResourceManager.GetString("Gyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affordable Adventure.
        /// </summary>
        public static string GyumriHeritage {
            get {
                return ResourceManager.GetString("GyumriHeritage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Culinary Love Letter.
        /// </summary>
        public static string GyumrisCulture {
            get {
                return ResourceManager.GetString("GyumrisCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri’s Must Visits.
        /// </summary>
        public static string GyumrisUniqueDistricts {
            get {
                return ResourceManager.GetString("GyumrisUniqueDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYUMRI.
        /// </summary>
        public static string GyumriUpperCase {
            get {
                return ResourceManager.GetString("GyumriUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostel.
        /// </summary>
        public static string Hostel {
            get {
                return ResourceManager.GetString("Hostel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to հ.
        /// </summary>
        public static string hourShort {
            get {
                return ResourceManager.GetString("hourShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Journey Through History, Culture, and Creativity.
        /// </summary>
        public static string JourneyThroughHistoryCultureCreativit {
            get {
                return ResourceManager.GetString("JourneyThroughHistoryCultureCreativit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the Interactive Map.
        /// </summary>
        public static string LearnaboutGyumrisdistricts {
            get {
                return ResourceManager.GetString("LearnaboutGyumrisdistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Plan Your Trip!.
        /// </summary>
        public static string LetsPlanYourTrip {
            get {
                return ResourceManager.GetString("LetsPlanYourTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move here, work remotely, open a business—or just experience everyday life like a local..
        /// </summary>
        public static string LiveAndWorkDesc {
            get {
                return ResourceManager.GetString("LiveAndWorkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want something new?.
        /// </summary>
        public static string LookingForMore {
            get {
                return ResourceManager.GetString("LookingForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you’re a local or a visitor, there’s always something new to uncover.Here’s where things get a little weird, wild, and wonderful. See More.
        /// </summary>
        public static string LookingForPartTextt {
            get {
                return ResourceManager.GetString("LookingForPartTextt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tucked in the northwestern corner of Armenia, Gyumri is a city that surprises you—not with skyscrapers or glitter, but with soul. It doesn&apos;t shout for attention. It whispers stories through its streets, scents, and sunsets. Here&apos;s why your next trip should bring you to this one-of-a-kind city..
        /// </summary>
        public static string MainArticleDesc {
            get {
                return ResourceManager.GetString("MainArticleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular Right Now.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        public static string Museum {
            get {
                return ResourceManager.GetString("Museum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        public static string night {
            get {
                return ResourceManager.GetString("night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Links.
        /// </summary>
        public static string OtherLinks {
            get {
                return ResourceManager.GetString("OtherLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        public static string Outdoor {
            get {
                return ResourceManager.GetString("Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a Trip.
        /// </summary>
        public static string PlanATrip {
            get {
                return ResourceManager.GetString("PlanATrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform was created as part of the
        /// &lt;strong&gt;&quot;Open Data Project for Accurate Visitor Information in Gyumri,&quot;&lt;/strong&gt; a sub-project within
        /// the &lt;strong&gt;&quot;Mayors for Economic Growth&quot;&lt;/strong&gt; grant program. The program is
        /// &lt;strong&gt;funded by the European Union&lt;/strong&gt; and &lt;strong&gt;implemented by UNDP&lt;/strong&gt;, with this
        /// project brought to life by the &lt;strong&gt;Gyumri Technology Center (GTC)&lt;/strong&gt; and
        /// &lt;strong&gt;Vanadzor Technology Center (VTC)&lt;/strong&gt; by the
        /// &lt;strong&gt;Enterprise Incubator Foundation [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Time Travel.
        /// </summary>
        public static string Point1 {
            get {
                return ResourceManager.GetString("Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Renaissance.
        /// </summary>
        public static string Point2 {
            get {
                return ResourceManager.GetString("Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri has always been Armenia&apos;s cultural capital—but lately, something new is stirring. The city&apos;s rich heritage in theater, music, and visual arts is fusing with a younger generation&apos;s bold experimentation. Painters, potters, coders, animators, filmmakers, and fashion designers are redefining what it means to be &quot;creative&quot; in Gyumri..
        /// </summary>
        public static string Point2Desc1 {
            get {
                return ResourceManager.GetString("Point2Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streets hum with creative energy: mural art on old facades, digital artists working out of tech hubs, handmade jewelry on display in boutique shops. Institutions like the Gyumri Technology Center and TUMO support a growing wave of innovation, blending tradition with tomorrow..
        /// </summary>
        public static string Point2Desc2 {
            get {
                return ResourceManager.GetString("Point2Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And it&apos;s not just about the art—it&apos;s about the atmosphere. You feel it in conversations at gallery openings. You hear it in the fusion of old folk melodies and electronic beats drifting from rehearsal rooms. You see it in workshops where Soviet tools are repurposed to make something entirely new..
        /// </summary>
        public static string Point2Desc3 {
            get {
                return ResourceManager.GetString("Point2Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Walking Supremacy.
        /// </summary>
        public static string Point3 {
            get {
                return ResourceManager.GetString("Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Gyumri, your feet are your best travel guide. The city was made for walking—not just because the layout is compact and scenic, but because the real magic happens when you take your time..
        /// </summary>
        public static string Point3Desc1 {
            get {
                return ResourceManager.GetString("Point3Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroll along Rustaveli Street and pop into an antique shop. Cut through a courtyard and find yourself in front of an impromptu nardi game. Sit on a public bench, and a local might start telling you about the earthquake, the artists, or the best ponchik in town..
        /// </summary>
        public static string Point3Desc2 {
            get {
                return ResourceManager.GetString("Point3Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no need for taxis, timetables, or noise-canceling headphones. The silence is soft, the air is fresh, and the streets reward the curious. You won&apos;t just get from point A to point B—you&apos;ll get a hundred little stories in between..
        /// </summary>
        public static string Point3Desc3 {
            get {
                return ResourceManager.GetString("Point3Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affordable Adventure.
        /// </summary>
        public static string Point4 {
            get {
                return ResourceManager.GetString("Point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s be honest—travel can get expensive. But in Gyumri, your money stretches without cutting corners on experience. You can enjoy a full homemade lunch, coffee, and dessert for the price of a metro ticket in most major cities. Boutique guesthouses offer character and comfort at a fraction of what you&apos;d pay elsewhere..
        /// </summary>
        public static string Point4Desc1 {
            get {
                return ResourceManager.GetString("Point4Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you&apos;re touring local museums, enjoying live music, or hopping into a marshrutka for a scenic countryside ride, you don&apos;t need to budget your joy. Even high-value experiences—like attending a puppet show, taking a pottery class, or spending an afternoon in a traditional bathhouse—are refreshingly affordable..
        /// </summary>
        public static string Point4Desc2 {
            get {
                return ResourceManager.GetString("Point4Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri proves that adventure doesn&apos;t have to be expensive. It just has to be real..
        /// </summary>
        public static string Point4Desc3 {
            get {
                return ResourceManager.GetString("Point4Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Culinary Love Letter.
        /// </summary>
        public static string Point5 {
            get {
                return ResourceManager.GetString("Point5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every city has a flavor, and Gyumri&apos;s is unforgettable. The day might begin with a breakfast of fresh cheese, herbs, and warm lavash from a corner bakery. By midday, you&apos;re hunting down the famous &quot;Ponchik Monchik&quot;—a hot, cream-filled doughnut so good it has its own legend..
        /// </summary>
        public static string Point5Desc1 {
            get {
                return ResourceManager.GetString("Point5Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch could bring you to a family-run fish restaurant, where trout from local rivers is served grilled and smoky, alongside roasted potatoes and pickled vegetables. You might sip homemade oghi (fruit vodka) with your host, or taste jams made from wild rose petals and walnuts..
        /// </summary>
        public static string Point5Desc2 {
            get {
                return ResourceManager.GetString("Point5Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And dinner? Maybe a cozy bistro in a renovated brick building, offering modern takes on traditional dishes—like lamb stew with herbs, or beetroot salads with garlic and walnuts. Every bite tells a story of land, season, and hospitality..
        /// </summary>
        public static string Point5Desc3 {
            get {
                return ResourceManager.GetString("Point5Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Gyumri, food isn&apos;t just sustenance. It&apos;s poetry..
        /// </summary>
        public static string Point5Desc4 {
            get {
                return ResourceManager.GetString("Point5Desc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Gyumri, every step is a step through time. The moment you enter the historic Kumayri district, you&apos;re surrounded by 19th-century buildings carved from the city&apos;s signature black tuff stone. Their thick walls and ornate wooden balconies have stood through earthquakes and empires, and they still hold the rhythm of old conversations and distant music..
        /// </summary>
        public static string PointDesc1 {
            get {
                return ResourceManager.GetString("PointDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep walking and you&apos;ll find splashes of color in unexpected places—Soviet-era mosaics tucked between courtyards, ironwork gates that creak with age, and fading shop signs in retro Cyrillic script. It&apos;s a rare kind of city where history hasn&apos;t just been preserved—it&apos;s lived in. Cafés operate out of century-old homes, and artisan workshops are nestled in what used to be merchant houses..
        /// </summary>
        public static string PointDesc2 {
            get {
                return ResourceManager.GetString("PointDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Gyumri, architecture isn&apos;t a background. It&apos;s a co-narrator..
        /// </summary>
        public static string PointDesc3 {
            get {
                return ResourceManager.GetString("PointDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Car.
        /// </summary>
        public static string PrivateCar {
            get {
                return ResourceManager.GetString("PrivateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From historic guesthouses to peaceful hideouts—rest the way Gyumri would want you to..
        /// </summary>
        public static string RelaxAndSleepDesc {
            get {
                return ResourceManager.GetString("RelaxAndSleepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re 120 km away from Gyumri.
        /// </summary>
        public static string RoutInfo {
            get {
                return ResourceManager.GetString("RoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you’re here for a day or a week, you’ll find stories, places, and people worth your time..
        /// </summary>
        public static string SeeAndDoDesc {
            get {
                return ResourceManager.GetString("SeeAndDoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email to send the plan.
        /// </summary>
        public static string SendEmailPlaceholder {
            get {
                return ResourceManager.GetString("SendEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sev Berd Fortress.
        /// </summary>
        public static string SevBerd {
            get {
                return ResourceManager.GetString("SevBerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An imposing 19th-century stronghold overlooking all of Gyumri..
        /// </summary>
        public static string SevBerdDesc {
            get {
                return ResourceManager.GetString("SevBerdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star of the Month..
        /// </summary>
        public static string StaroftheMonth {
            get {
                return ResourceManager.GetString("StaroftheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start from:.
        /// </summary>
        public static string StartFrom {
            get {
                return ResourceManager.GetString("StartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Workshop with Local Artisans.
        /// </summary>
        public static string TakeWorkshopWithLocalArtisans {
            get {
                return ResourceManager.GetString("TakeWorkshopWithLocalArtisans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri is a city of makers..
        /// </summary>
        public static string TakeWorkshopWithLocalArtisansText {
            get {
                return ResourceManager.GetString("TakeWorkshopWithLocalArtisansText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your.
        /// </summary>
        public static string TakeYour {
            get {
                return ResourceManager.GetString("TakeYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        public static string Taxi {
            get {
                return ResourceManager.GetString("Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This isn&apos;t just a website—it&apos;s a tool to make Gyumri more visible, accessible, and welcoming, for visitors
        ///    and locals alike..
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavors Passed Down Through Time and Stone.
        /// </summary>
        public static string TraditionMeetsModernity {
            get {
                return ResourceManager.GetString("TraditionMeetsModernity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerevan, Northern Bus Station.
        /// </summary>
        public static string TrainAddress {
            get {
                return ResourceManager.GetString("TrainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel duration.
        /// </summary>
        public static string TravelDuration {
            get {
                return ResourceManager.GetString("TravelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tool to organize your travel, stay, and activities for an unforgettable trip to Gyumri. Get a personalized plan emailed or downloaded at the end!.
        /// </summary>
        public static string TripPageText {
            get {
                return ResourceManager.GetString("TripPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trip plan.
        /// </summary>
        public static string TripPlan {
            get {
                return ResourceManager.GetString("TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip to Gyumri.
        /// </summary>
        public static string TripToGyumri {
            get {
                return ResourceManager.GetString("TripToGyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forging Identity in the Fires of Tradition.
        /// </summary>
        public static string UNESCOսBlacksmithingMasterpieces {
            get {
                return ResourceManager.GetString("UNESCOսBlacksmithingMasterpieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varem &amp; Marem Art Studio.
        /// </summary>
        public static string VaremMarem {
            get {
                return ResourceManager.GetString("VaremMarem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whimsical, handmade ceramic magic you won’t forget..
        /// </summary>
        public static string VaremMaremDesc {
            get {
                return ResourceManager.GetString("VaremMaremDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        public static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday, Saturday, Sunday  .
        /// </summary>
        public static string WeekDayTrain {
            get {
                return ResourceManager.GetString("WeekDayTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Reasons to Come to Gyumri.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open city where innovations, arts and crafts, traditions, and humor are born. &lt;br&gt;Armenia’s cultural soul and creative spirit in one walkable city..
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Gyumri.
        /// </summary>
        public static string WelcomeGyumri {
            get {
                return ResourceManager.GetString("WelcomeGyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A city where every street corner holds a story—and every visit leaves one behind..
        /// </summary>
        public static string WelcomeSubHeadline {
            get {
                return ResourceManager.GetString("WelcomeSubHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to Do.
        /// </summary>
        public static string WhatToDo {
            get {
                return ResourceManager.GetString("WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to Stay.
        /// </summary>
        public static string WheretoStay {
            get {
                return ResourceManager.GetString("WheretoStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready when you are..
        /// </summary>
        public static string WhyReady {
            get {
                return ResourceManager.GetString("WhyReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because it&apos;s not trying to be like anywhere else. It&apos;s not racing to keep up with trends. It&apos;s walking to its own rhythm—inviting you to slow down, look closer, and stay longer..
        /// </summary>
        public static string WhyReason {
            get {
                return ResourceManager.GetString("WhyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So why come to Gyumri?.
        /// </summary>
        public static string WhySection {
            get {
                return ResourceManager.GetString("WhySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerevan.
        /// </summary>
        public static string Yerevan {
            get {
                return ResourceManager.GetString("Yerevan", resourceCulture);
            }
        }
    }
}
