//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GyumriFinalVersion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GyumriFinalVersion.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and explore.
        /// </summary>
        public static string AndExplore {
            get {
                return ResourceManager.GetString("AndExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Time Travel.
        /// </summary>
        public static string ArchitecturalTimeTravel {
            get {
                return ResourceManager.GetString("ArchitecturalTimeTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aregak Bakery and Cafe.
        /// </summary>
        public static string AregakBakery {
            get {
                return ResourceManager.GetString("AregakBakery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Art, Tech, and Tradition Collide.
        /// </summary>
        public static string ArtTechTraditionCollide {
            get {
                return ResourceManager.GetString("ArtTechTraditionCollide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baked with Love, Served with Purpose..
        /// </summary>
        public static string BakedwithLove {
            get {
                return ResourceManager.GetString("BakedwithLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural Renaissance.
        /// </summary>
        public static string CulturalRenaissance {
            get {
                return ResourceManager.GetString("CulturalRenaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our coupon feature is on the way – check back soon for.
        /// </summary>
        public static string CuponFeature {
            get {
                return ResourceManager.GetString("CuponFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUPON.
        /// </summary>
        public static string CuponUpperCase {
            get {
                return ResourceManager.GetString("CuponUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the Heart of Armenia.
        /// </summary>
        public static string DiscovertheHeartofArmenia {
            get {
                return ResourceManager.GetString("DiscovertheHeartofArmenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the obvious..
        /// </summary>
        public static string DiveDeeperIntoGyumrisHiddenGems {
            get {
                return ResourceManager.GetString("DiveDeeperIntoGyumrisHiddenGems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Gyumri After Dark.
        /// </summary>
        public static string ExperienceGyumriAfterDark {
            get {
                return ResourceManager.GetString("ExperienceGyumriAfterDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city comes alive in a different way after sunset..
        /// </summary>
        public static string ExperienceGyumriAfterDarkText {
            get {
                return ResourceManager.GetString("ExperienceGyumriAfterDarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the Underground Arts Scene.
        /// </summary>
        public static string ExploretheUndergroundArtsScene {
            get {
                return ResourceManager.GetString("ExploretheUndergroundArtsScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri’s arts scene isn’t limited to its galleries and theaters..
        /// </summary>
        public static string ExploretheUndergroundArtsSceneText {
            get {
                return ResourceManager.GetString("ExploretheUndergroundArtsSceneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing.
        /// </summary>
        public static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge of Legends.
        /// </summary>
        public static string ForgeOfLegends {
            get {
                return ResourceManager.GetString("ForgeOfLegends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Empires to Earthquakes.
        /// </summary>
        public static string FromEmpirestoEarthquakes {
            get {
                return ResourceManager.GetString("FromEmpirestoEarthquakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next: Getting Here.
        /// </summary>
        public static string GettingHere {
            get {
                return ResourceManager.GetString("GettingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting to/around.
        /// </summary>
        public static string GettingToAround {
            get {
                return ResourceManager.GetString("GettingToAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting to Gyumri.
        /// </summary>
        public static string GettingtoGyumri {
            get {
                return ResourceManager.GetString("GettingtoGyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great deals!.
        /// </summary>
        public static string greatDeals {
            get {
                return ResourceManager.GetString("greatDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri.
        /// </summary>
        public static string Gyumri {
            get {
                return ResourceManager.GetString("Gyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri&apos;s Heritage.
        /// </summary>
        public static string GyumriHeritage {
            get {
                return ResourceManager.GetString("GyumriHeritage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri&apos;s Culture.
        /// </summary>
        public static string GyumrisCulture {
            get {
                return ResourceManager.GetString("GyumrisCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri s Must Visits.
        /// </summary>
        public static string GyumrisUniqueDistricts {
            get {
                return ResourceManager.GetString("GyumrisUniqueDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYUMRI.
        /// </summary>
        public static string GyumriUpperCase {
            get {
                return ResourceManager.GetString("GyumriUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Journey Through History, Culture, and Creativit.
        /// </summary>
        public static string JourneyThroughHistoryCultureCreativit {
            get {
                return ResourceManager.GetString("JourneyThroughHistoryCultureCreativit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the Interactive Map.
        /// </summary>
        public static string LearnaboutGyumrisdistricts {
            get {
                return ResourceManager.GetString("LearnaboutGyumrisdistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Plan Your Trip!.
        /// </summary>
        public static string LetsPlanYourTrip {
            get {
                return ResourceManager.GetString("LetsPlanYourTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want something new?.
        /// </summary>
        public static string LookingForMore {
            get {
                return ResourceManager.GetString("LookingForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you’re a local or a visitor, there’s always something new to uncover.Here’s where things get a little weird, wild, and wonderful. See More.
        /// </summary>
        public static string LookingForPartTextt {
            get {
                return ResourceManager.GetString("LookingForPartTextt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        public static string night {
            get {
                return ResourceManager.GetString("night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a Trip.
        /// </summary>
        public static string PlanATrip {
            get {
                return ResourceManager.GetString("PlanATrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Car.
        /// </summary>
        public static string PrivateCar {
            get {
                return ResourceManager.GetString("PrivateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re 120 km away from Gyumri.
        /// </summary>
        public static string RoutInfo {
            get {
                return ResourceManager.GetString("RoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star of the Month..
        /// </summary>
        public static string StaroftheMonth {
            get {
                return ResourceManager.GetString("StaroftheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Workshop with Local Artisans.
        /// </summary>
        public static string TakeWorkshopWithLocalArtisans {
            get {
                return ResourceManager.GetString("TakeWorkshopWithLocalArtisans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyumri is a city of makers..
        /// </summary>
        public static string TakeWorkshopWithLocalArtisansText {
            get {
                return ResourceManager.GetString("TakeWorkshopWithLocalArtisansText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your.
        /// </summary>
        public static string TakeYour {
            get {
                return ResourceManager.GetString("TakeYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        public static string Taxi {
            get {
                return ResourceManager.GetString("Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradition Meets Modernity.
        /// </summary>
        public static string TraditionMeetsModernity {
            get {
                return ResourceManager.GetString("TraditionMeetsModernity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tool to organize your travel, stay, and activities for an unforgettable trip to Cymru. Get a personalized plan emailed or downloaded at the end!.
        /// </summary>
        public static string TripPageText {
            get {
                return ResourceManager.GetString("TripPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trip plan.
        /// </summary>
        public static string TripPlan {
            get {
                return ResourceManager.GetString("TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNESCO’s Blacksmithing Masterpieces.
        /// </summary>
        public static string UNESCOսBlacksmithingMasterpieces {
            get {
                return ResourceManager.GetString("UNESCOսBlacksmithingMasterpieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Reasons to Come to Gyumri.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open city where innovations, arts and crafts, traditions, and humor are born. &lt;br&gt;Armenia’s cultural soul and creative spirit in one walkable city..
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Gyumri.
        /// </summary>
        public static string WelcomeGyumri {
            get {
                return ResourceManager.GetString("WelcomeGyumri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to Do.
        /// </summary>
        public static string WhatToDo {
            get {
                return ResourceManager.GetString("WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to Stay.
        /// </summary>
        public static string WheretoStay {
            get {
                return ResourceManager.GetString("WheretoStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerevan.
        /// </summary>
        public static string Yerevan {
            get {
                return ResourceManager.GetString("Yerevan", resourceCulture);
            }
        }
    }
}
